version: 2

jobs:
  build:
    docker:
      - image: cimg/base:2022.03
    steps:
      - checkout
      - run:
          name: Installing GCC
          command: 'sudo apt-get update && sudo apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'sudo apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Install Boost
          command: 'sudo apt-get update && sudo apt-get install -y libboost-all-dev'
      - run:
          name: "Pull Submodules"
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files.
          command: 'cmake --build build'
