%YAML 1.2
---
gpu: 0

checkpoint: models/maia-1900/ckpt/ckpt-40

dataset:
  input_train: '../data/laststep_gz_files/training/*/*' # This uses glob so training/*/* is probably the end
  input_test: '../data/laststep_gz_files/validation/*/*' # This uses glob so validate/*/* is probably the end

training:
    precision: 'half'
    batch_size: 2048
    num_batch_splits: 1
    test_steps: 2000
    train_avg_report_steps: 500
    total_steps: 800000
    checkpoint_steps: 10000
    shuffle_size: 250000
    lr_values:
        # - 0.1
        # - 0.01
        - 0.001
        - 0.0001
    lr_boundaries:
        # - 480000
        # - 600000
        - 160000
    policy_loss_weight: 1.0            # weight of policy loss
    value_loss_weight: 1.0             # weight of value loss

model:
  filters: 64
  residual_blocks: 6
  se_ratio: 8
...
